### ISSUE TITLE
Issue with matplotlib 

### ISSUE THREAD

**Issue by neogyk** [aelwood/hepML#3]
**I got this runtime error during executing run.py:**

(hepML) bash-4.1$ python run.py 
Traceback (most recent call last):
  File "run.py", line 7, in <module>
    from dfConvert import convertTree
  File "../user/<username>/hepML/hepML/dfConvert.py", line 6, in <module>
    import matplotlib.pyplot as plt
  File "../user/<username>/anaconda2/envs/hepML/lib/ROOT.py", line 301, in _importhook
    return _orig_ihook( name, *args, **kwds )
  File "..//user/<username>/anaconda2/envs/hepML/lib/python2.7/site-packages/matplotlib/pyplot.py", line 31, in <module>
    import matplotlib.colorbar
  File "../user/<username>/anaconda2/envs/hepML/lib/ROOT.py", line 301, in _importhook
    return _orig_ihook( name, *args, **kwds )
  File "../user/<username>/anaconda2/envs/hepML/lib/python2.7/site-packages/matplotlib/colorbar.py", line 32, in <module>
    import matplotlib.artist as martist
  File "../user/<username>/anaconda2/envs/hepML/lib/ROOT.py", line 301, in _importhook
    return _orig_ihook( name, *args, **kwds )
  File "../user/<username>/anaconda2/envs/hepML/lib/python2.7/site-packages/matplotlib/artist.py", line 16, in <module>
    from .path import Path
  File "../user/<username>/anaconda2/envs/hepML/lib/ROOT.py", line 301, in _importhook
    return _orig_ihook( name, *args, **kwds )
  File "../user/<username>/anaconda2/envs/hepML/lib/python2.7/site-packages/matplotlib/path.py", line 21, in <module>
    from . import _path, rcParams
  File "../user/<username>/anaconda2/envs/hepML/lib/ROOT.py", line 301, in _importhook
    return _orig_ihook( name, *args, **kwds )
ImportError: ../user/<username>/anaconda2/envs/hepML/lib/./libstdc++.so.6: version `CXXABI_1.3.9' not found (required by ../user/<username>/anaconda2/envs/hepML/lib/python2.7/site-packages/matplotlib/_path.so)

**Could you please give the advice - how to fix this issue?**

**Comment by neogyk** [comment]
In my case this issue solved by relinking shared libraries:

1.` rm libstdc++.so.6`
2.`ln -s libstdc++.so.6.0.24 libstdc++.so.6`
